[project]
name = 'dao-platform'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.dao-core]
path = 'contracts/dao-core.clar'
clarity_version = 2
epoch = 2.5

[contracts.governance-token]
path = 'contracts/governance-token.clar'
clarity_version = 2
epoch = 2.5


[contracts.proposal-excecution]
path = 'contracts/proposal-excecution.clar'
clarity_version = 2
epoch = 2.5


[contracts.traits]
path = 'contracts/traits.clar'
clarity_version = 2
epoch = 2.5

[contracts.treasury]
path = 'contracts/treasury.clar'
clarity_version = 2
epoch = 2.5


[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
